# Generated by Django 3.1 on 2020-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_organization_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='name',
            new_name='con_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='org_name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='prob_name',
        ),
    ]
