# Generated by Django 3.1 on 2020-05-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20200522_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='con_name',
            new_name='contest_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='prob_name',
            new_name='problem_name',
        ),
    ]
