# Generated by Django 3.1 on 2020-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20200522_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='judge_link',
            field=models.URLField(blank=True),
        ),
    ]
