# Generated by Django 3.1 on 2020-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
