# Generated by Django 3.1 on 2020-05-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_problem_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='judge_link',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='text',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_judge',
            field=models.URLField(blank=True),
        ),
    ]
