# Generated by Django 3.1 on 2020-05-22 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_auto_20200522_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
